import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';

// --- START: MODIFICATIONS ---

// 1. Remove the original import: import 'package:firebase_auth/firebase_auth.dart';
// 2. Add the aliased import (This resolves the conflict):
import 'package:firebase_auth/firebase_auth.dart' as fb_auth_lib;

// --- END: MODIFICATIONS ---

import 'firebase_options.dart'; // IMPORTANT: This file is generated by FlutterFire CLI

// Import pages
import 'pages/auth/login_screen.dart';
import 'pages/auth/signup_screen.dart';
import 'pages/auth/verify_otp_screen.dart';
import 'pages/auth/forgot_password_screen.dart';
import 'pages/auth/change_password_screen.dart';

import 'pages/profile_screen.dart';
import 'pages/edit_profile_screen.dart';
import 'pages/main_screen.dart';
import 'pages/report_found_screen.dart';
import 'pages/report_lost_screen.dart';
import 'pages/my_posts_screen.dart';

// Import providers
import 'providers/auth_provider.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Ensure you run 'flutterfire configure' to generate firebase_options.dart
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(
    MultiProvider(
      providers: [ChangeNotifierProvider(create: (_) => AuthProvider())],
      child: const MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Django Firebase Auth',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue, // MaterialColor closest to blueAccent
        primaryColor: Colors.blueAccent,
        fontFamily: 'Inter',
        appBarTheme: const AppBarTheme(
          backgroundColor: Colors.blueAccent,
          foregroundColor: Colors.white,
          titleTextStyle: TextStyle(
            color: Colors.white,
            fontSize: 23,
            fontWeight: FontWeight.bold,
          ),
        ),
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            backgroundColor: Colors.blueAccent,
            foregroundColor: Colors.white,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
            padding: const EdgeInsets.symmetric(vertical: 16),
            textStyle: const TextStyle(
              fontSize: 16,
              fontWeight: FontWeight.bold,
            ),
          ),
        ),
        inputDecorationTheme: InputDecorationTheme(
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12),
            borderSide: const BorderSide(color: Colors.blueAccent),
          ),
          focusedBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12),
            borderSide: const BorderSide(color: Colors.blueAccent, width: 2),
          ),
          contentPadding: const EdgeInsets.all(16),
        ),
      ),
      home: const AuthGate(),
      onGenerateRoute: (settings) {
        // Handle routes with arguments
        if (settings.name == '/verify-otp') {
          final args = settings.arguments as Map<String, dynamic>?;
          return MaterialPageRoute(
            builder:
                (context) => VerifyOTPScreen(
                  email: args?['email'] ?? '',
                  firebaseUid: args?['firebaseUid'] ?? '',
                ),
          );
        }

        // Default routes without arguments
        final routes = <String, WidgetBuilder>{
          '/login': (context) => const LoginScreen(),
          '/signup': (context) => const SignUpScreen(),
          '/forgot-password': (context) => const ForgotPasswordScreen(),
          '/change-password': (context) => const ChangePasswordScreen(),
          '/home': (context) => const MainScreen(), // Updated to MainScreen
          '/profile': (context) => const ProfileScreen(),
          '/edit-profile': (context) => const EditProfileScreen(),
          '/report-found': (context) => const ReportFoundScreen(),
          '/report-lost': (context) => const ReportLostScreen(),
          '/my-posts': (context) => const MyPostsScreen(),
        };

        final builder = routes[settings.name];
        if (builder != null) {
          return MaterialPageRoute(builder: builder);
        }

        return null;
      },
    );
  }
}

// Authentication Gate to manage navigation based on auth state
class AuthGate extends StatelessWidget {
  const AuthGate({super.key});

  @override
  Widget build(BuildContext context) {
    // --- START: MODIFICATIONS ---

    // 1. User type must now be prefixed: User? -> fb_auth_lib.User?
    return StreamBuilder<fb_auth_lib.User?>(
      // 2. FirebaseAuth must now be prefixed: FirebaseAuth.instance
      stream: fb_auth_lib.FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        // Show loading spinner while checking auth state
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            body: Center(child: CircularProgressIndicator()),
          );
        }

        // If the user is logged in, show the Main Screen
        if (snapshot.hasData) {
          return MainScreen(key: MainScreen.navigatorKey);
        } else {
          // Otherwise, show the Login Screen
          return const LoginScreen();
        }
      },
    );

    // --- END: MODIFICATIONS ---
  }
}
