# Generated by Django 4.2.2 on 2025-12-05 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_user_id_userprofile_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('item_name', models.CharField(max_length=200)),
                ('item_img', models.ImageField(blank=True, null=True, upload_to='found_items/')),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Documents', 'Documents'), ('Luggage', 'Luggage'), ('Apparel', 'Apparel'), ('Accessories', 'Accessories'), ('Pets', 'Pets'), ('Keys', 'Keys'), ('Money', 'Money'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('color', models.CharField(max_length=100)),
                ('location', models.CharField(help_text='Location where item was found', max_length=200)),
                ('date', models.DateField(help_text='Date when item was found')),
                ('status', models.CharField(default='found', max_length=20)),
                ('posted_time', models.DateTimeField(auto_now_add=True)),
                ('owner_identified', models.BooleanField(default=False)),
                ('original_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_items', to='core.userprofile')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_items', to='core.userprofile')),
            ],
            options={
                'verbose_name': 'Found Item',
                'verbose_name_plural': 'Found Items',
                'ordering': ['-posted_time'],
            },
        ),
    ]
