# Generated by Django 4.2.2 on 2025-12-09 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_lostitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='founditem',
            old_name='original_owner',
            new_name='owner_id',
        ),
        migrations.RenameField(
            model_name='lostitem',
            old_name='original_owner',
            new_name='finder_id',
        ),
        migrations.RenameField(
            model_name='lostitem',
            old_name='owner_identified',
            new_name='finder_identified',
        ),
    ]
