# Generated by Django 5.2.7 on 2025-12-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_original_owner_founditem_owner_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditem',
            name='color',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='item_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='location',
            field=models.CharField(help_text='Location where item was found', max_length=60),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='status',
            field=models.CharField(default='found', max_length=5),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='color',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='item_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='location',
            field=models.CharField(help_text='Location where item was lost', max_length=60),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='status',
            field=models.CharField(default='lost', max_length=5),
        ),
    ]
