# Generated by Django 4.2.2 on 2025-12-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_founditem_color_alter_founditem_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='found_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lost_count',
            field=models.IntegerField(default=0),
        ),
    ]
