# Generated by Django 4.2.2 on 2025-12-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userprofile_found_count_userprofile_lost_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founditem',
            name='color',
        ),
        migrations.RemoveField(
            model_name='lostitem',
            name='color',
        ),
        migrations.AddField(
            model_name='founditem',
            name='color_id',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='founditem',
            name='color_name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='color_id',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='color_name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
