# Generated by Django 4.2.2 on 2026-02-11 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnershipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='core.userprofile')),
                ('found_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_requests', to='core.founditem')),
                ('lost_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_requests', to='core.lostitem')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='core.userprofile')),
            ],
            options={
                'verbose_name': 'Ownership Request',
                'verbose_name_plural': 'Ownership Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
