# Generated by Django 4.2.2 on 2026-02-12 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_ownershiprequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
    ]
