# Generated by Django 4.2.2 on 2026-02-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_opened',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
