# Generated by Django 4.2.2 on 2026-02-18 04:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_userprofile_last_opened'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='joined_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
