# Generated by Django 4.2.2 on 2026-02-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_userprofile_joined_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='info',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='info',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
    ]
