# Generated by Django 4.2.2 on 2026-02-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_founditem_info_lostitem_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='matched_post',
            field=models.CharField(blank=True, default='None', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='matched_post',
            field=models.CharField(blank=True, default='None', max_length=50, null=True),
        ),
    ]
