# Generated by Django 4.2.2 on 2026-02-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_matched_post_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportIssue',
            fields=[
                ('issue_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('post_id', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=200)),
                ('reported_user_id', models.CharField(max_length=60)),
                ('issue_status', models.CharField(choices=[('Not Responded', 'Not Responded'), ('Responded', 'Responded')], default='Not Responded', max_length=20)),
                ('issue_category', models.CharField(choices=[('Fake Post', 'Fake Post'), ('Technical Bug', 'Technical Bug'), ('Harassment', 'Harassment'), ('Wrong Owner Assigned', 'Wrong Owner Assigned'), ('Other', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('proof_doc_1', models.FileField(blank=True, null=True, upload_to='report_proofs/')),
                ('proof_doc_2', models.FileField(blank=True, null=True, upload_to='report_proofs/')),
                ('posted_by', models.CharField(max_length=60)),
                ('posted_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Report Issue',
                'verbose_name_plural': 'Report Issues',
                'ordering': ['-posted_time'],
            },
        ),
    ]
