# Generated by Django 5.2.7 on 2026-02-21 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_report_issue_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('post_id', models.CharField(max_length=50)),
                ('reported_user_id', models.CharField(max_length=60)),
                ('issuer_user_id', models.CharField(max_length=60)),
                ('review_status', models.CharField(choices=[('Resolved', 'Resolved'), ('Dismissed', 'Dismissed')], default='Resolved', max_length=20)),
                ('review_category', models.CharField(choices=[('Action Taken', 'Action Taken'), ('No Action Required', 'No Action Required'), ('Warning Sent to User', 'Warning Sent to User'), ('Post Removed', 'Post Removed'), ('User Permanently Banned', 'User Permanently Banned')], max_length=50)),
                ('description', models.TextField()),
                ('reviewed_by', models.CharField(max_length=60)),
                ('reviewed_time', models.DateTimeField(auto_now_add=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='core.reportissue')),
            ],
        ),
    ]
