# Generated by Django 4.2.2 on 2026-02-26 19:06

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_reviewissue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewissue',
            options={'ordering': ['-reviewed_time'], 'verbose_name': 'Review Issue', 'verbose_name_plural': 'Review Issues'},
        ),
        migrations.RemoveField(
            model_name='reviewissue',
            name='id',
        ),
        migrations.RemoveField(
            model_name='reviewissue',
            name='report',
        ),
        migrations.AddField(
            model_name='reviewissue',
            name='report_id',
            field=models.CharField(default='default_id', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='founditem',
            name='item_img',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.found_item_img_path),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='item_img',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.lost_item_img_path),
        ),
        migrations.AlterField(
            model_name='reportissue',
            name='proof_doc_1',
            field=models.FileField(blank=True, null=True, upload_to=core.models.report_proof_1_path),
        ),
        migrations.AlterField(
            model_name='reportissue',
            name='proof_doc_2',
            field=models.FileField(blank=True, null=True, upload_to=core.models.report_proof_2_path),
        ),
        migrations.AlterField(
            model_name='reviewissue',
            name='review_category',
            field=models.CharField(choices=[('Action Taken', 'Action Taken'), ('No Action Required', 'No Action Required'), ('Warning Sent to User', 'Warning Sent to User'), ('Post Removed', 'Post Removed'), ('User Permanently Banned', 'User Permanently Banned')], max_length=30),
        ),
        migrations.AlterField(
            model_name='reviewissue',
            name='review_id',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
