# Generated by Django 4.2.2 on 2026-03-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_emailotp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='user_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
