# Generated by Django 5.2.7 on 2026-03-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_emailotp_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditem',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='location',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='location',
            field=models.CharField(max_length=60),
        ),
    ]
