# Generated by Django 5.2.7 on 2026-03-22 09:42

import cloudinary_storage.storage
import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_founditem_date_alter_founditem_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportissue',
            name='proof_doc_1',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=core.models.report_proof_1_path),
        ),
        migrations.AlterField(
            model_name='reportissue',
            name='proof_doc_2',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=core.models.report_proof_2_path),
        ),
    ]
