# Generated by Django 5.2.7 on 2026-03-22 09:47

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_reportissue_proof_doc_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportissue',
            name='proof_doc_1',
            field=models.FileField(blank=True, null=True, upload_to=core.models.report_proof_1_path),
        ),
        migrations.AlterField(
            model_name='reportissue',
            name='proof_doc_2',
            field=models.FileField(blank=True, null=True, upload_to=core.models.report_proof_2_path),
        ),
    ]
