# Generated by Django 5.2.7 on 2026-03-26 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_reportissue_proof_doc_1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailOTP',
        ),
    ]
